# Generated by Django 6.0.2 on 2026-02-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='education',
            new_name='degree',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='availability',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
