# Generated by Django 6.0.2 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_proof',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/enrollment_proofs/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id_card',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/id_cards/'),
        ),
    ]
