# Generated by Django 6.0.2 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_enrollment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
