# Generated by Django 6.0.2 on 2026-05-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clientprofile_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Freelancer'), ('client', 'Client')], max_length=20),
        ),
    ]
