# Generated by Django 6.0.2 on 2026-05-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_category_parent_seed_qurikly_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gigs.category',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gigs.category',),
        ),
    ]
